name: master & PR
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version:
          - "6.1"
          - "7.0"
          - "7.1"
        ruby_version:
          - "3.1"
          - "3.2"
          - "3.3"
        autoloader:
          - "zeitwerk"
        eager_load:
          - "true"
          - "false"
    name: Test on Rails ${{ matrix.rails_version }} & Ruby ${{ matrix.ruby_version }} & EagerLoad ${{ matrix.eager_load }}
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile_rails_${{ matrix.rails_version }}.rb
      CI: true
      EAGER_LOAD: ${{ matrix.eager_load }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: rspec
        run: bundle exec rspec
      - name: Coveralls
        if: matrix.rails_version == '7.1' && matrix.ruby_version == '3.3'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
