name: master & PR
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version:
          - "5.0"
          - "5.1"
          - "5.2"
          - "6.0"
          - "6.1"
          - "7.0"
        ruby_version:
          - "2.7"
          - "3.1"
        autoloader:
          - "zeitwerk"
          - "classic"
        eager_load:
          - "true"
          - "false"
        exclude:
          - rails_version: "5.0"
            ruby_version: "3.1"
          - rails_version: "5.1"
            ruby_version: "3.1"
          - rails_version: "5.2"
            ruby_version: "3.1"
          - rails_version: "5.0"
            autoloader: "zeitwerk"
          - rails_version: "5.1"
            autoloader: "zeitwerk"
          - rails_version: "5.2"
            autoloader: "zeitwerk"
          - rails_version: "5.0"
            autoloader: "classic"
          - rails_version: "5.1"
            autoloader: "classic"
          - rails_version: "5.2"
            autoloader: "classic"
    name: Test on Rails ${{ matrix.rails_version }} & Ruby ${{ matrix.ruby_version }} & Autoloader ${{ matrix.autoloader }} & EagerLoad ${{ matrix.eager_load }}
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile_rails_${{ matrix.rails_version }}.rb
      CI: true
      EAGER_LOAD: ${{ matrix.eager_load }}
      AUTOLOADER : ${{ matrix.autoloader }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: rspec
        run: bundle exec rspec
      - name: Coveralls
        if: matrix.rails_version == '6.1' && matrix.ruby_version == '3.1'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
